# Jekyll configuration

name: The Polifonia Ecosystem
description: Overview and documentation of the Polifonia Project data and software components
main-project-url: https://polifonia-project.eu/

# url is currently only used only for the RSS feed in feed.xml
url: https://polifonia-project.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: "ecosystem"
#baseurl: ""


rdf:
    namespace: "http://w3id.org/polifonia/ecosystem/"

reeco:
    validate: false

# just-the-docs
#theme: "just-the-docs"
logo: "/assets/images/polifonia-black.png"
# Aux links for the upper right navigation
aux_links:
  "Polifonia on Github":
    - "//github.com/polifonia-project"

heading_anchors: true
# Color scheme supports "light" (default) and "dark"
color_scheme: polifonia


# These can be '' to hide the Github or Gitlab nav buttons
github: 'polifonia-project'
gitlab: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

#permalink: /:path.html

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

plugins: [jekyll-paginate]

exclude: [ '.git' ]

collections_dir: content/

collections:
    polifonia-project:
        output: true
    smashub:
        output: true
# project:
    #     output: true
#
# stories:
#     output: true
# external-components:
#     output: true
# lharp:
#     output: true
# ontology-network:
#     output: true
# sonar2021_data_transformation:
#     output: true
# sonar2021_demo:
#     output: true
# textual-corpus-population:
#     output: true
# documentary-evidence-benchmark:
#     output: true
# rulebook:
#     output: true
# core:
#     output: true
# instrument:
#     output: true
# musical-performance:
#     output: true
# ocr:
#     output: true
# folk_ngram_analysis:
#     output: true
# patterns:
#     output: true
# registry_app:
#     output: true
# source:
#     output: true

defaults:
  - scope:
      type: polifonia-project
    values:
      layout: component
  - scope:
      type: smashub
    values:
      layout: component
  - scope:
      #type: project
      path: pages/work-packages
    values:
      identifier: "wppage"
  - scope:
      #type: project
      path: pages/pilots
    values:
      identifier: "pilotpage"
# - scope:
#     type: stories
#   values:
#     layout: story
# - scope:
#     type: rulebook
#   values:
#     layout: component
# - scope:
#     type: documentary-evidence-benchmark
#   values:
#     layout: component
# - scope:
#     type: lharp
#   values:
#     layout: component
# - scope:
#     type: ontology-network
#   values:
#     layout: component
# - scope:
#     type: sonar2021_data_transformation
#   values:
#     layout: component
# - scope:
#     type: sonar2021_demo
#   values:
#     layout: component
# - scope:
#     type: textual-corpus-population
#   values:
#     layout: component
# - scope:
#     type: external-components
#   values:
#     layout: component
# - scope:
#     type: core
#   values:
#     layout: component
# - scope:
#     type: folk_ngram_analysis
#   values:
#     layout: component
# - scope:
#     type: registry_app
#   values:
#     layout: component


just_the_docs:
  search_enabled: true
  search:
      # Split pages into sections that can be searched individually
      # Supports 1 - 6, default: 2
      heading_level: 2
      # Maximum amount of previews per search result
      # Default: 3
      previews: 3
      # Maximum amount of words to display before a matched word in the preview
      # Default: 5
      preview_words_before: 5
      # Maximum amount of words to display after a matched word in the preview
      # Default: 10
      preview_words_after: 10
      # Set the search token separator
      # Default: /[\s\-/]+/
      # Example: enable support for hyphenated search words
      tokenizer_separator: /[\s/]+/
      # Display the relative url in search results
      # Supports true (default) or false
      rel_url: true
      # Enable or disable the search button that appears in the bottom right corner of every page
      # Supports true or false (default)
      button: false
  collections:
    polifonia-project:
      name: polifonia-project
      nav_exclude: true
      search_exclude: false
    smashub:
      name: smashub
      nav_exclude: true
      search_exclude: false
    # rulebook:
    #   name: rulebook
    #   nav_exclude: true
    #   search_exclude: false
    # stories:
    #   name: Stories
    #   nav_exclude: true
    #   search_exclude: false
    # folk_ngram_analysis:
    #   name: folk_ngram_analysis
    #   nav_exclude: true
    #   search_exclude: false
      
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - LICENSE
 - README.md
 - "*.py"
 - "*.owl"
 - "*.ipynb"

